Wakanda 001
SpectreLion/remindMeApp-1 pull request #2
Opened 2018-03-28 23:35 UTC by mex-jpv

Se hicieron dos commits, el segundo solo se cambio task:{} de clase.

2018-03-29 00:17 UTC, jaycorpstudios requested changes
en general va bien la implementación, pero necesitas resolver los comentarios que te agregué, sobre todo por que tu branch no compila en este momento.

2018-03-29 00:17 UTC, jaycorpstudios commented on src/modals/AddTaskModal.js
> +import DatePicker from 'react-native-datepicker';
Ok, primero que nada, no veo esta dependencia en el package.json probablemente lo instalaste localmente y funcionó para ti, pero cualquiera que descargue tu branch para una prueba va a encontrar un fallo al momento de correr la aplicación, necesitas agregar la dependencia manualmente al package o agregar la bandera de save cuando lo instalas para que modifique el package.

Suponiendo que esta fue la dependencia que instalaste: 
npm install react-native-datepicker --save

2018-03-29 00:17 UTC, jaycorpstudios commented on src/modals/AddTaskModal.js
> +import moment from 'moment'
asumo que lo mismo con esta de moment, pero antes que nada, **realmente necesitas moment**? no puedes hacerlo con lo que ya sabes sobre fechas en JS?

2018-03-29 00:17 UTC, jaycorpstudios commented on src/modals/AddTaskModal.js
> +      date:''
agregar el date esta bien aquí, pero por que lo inicializas como un string? no sería mejor inicializarlo con la fecha actual aquí? Es decir cada que el componente arranque va a fijar la fecha actual.

2018-03-29 00:17 UTC, jaycorpstudios commented on src/modals/AddTaskModal.js
> +      months =['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'];
hasta aquí ya hemos usado este arreglo de months en mas de un lugar... me parece que lo utilizamos en el componente del TaskHeader... como buena práctica no debemos replicar código, entonces:

Mueve este arreglo a un archivo de datos estáticos, algo parecido a lo que hicimos con los estados de las tareas iniciales. puede quedar dentro del folder de staticData con el nombre que te haga mas sentido.

Importa ese archivo a los componentes que lo requieran, es decir aquí y en TaskHeader.

2018-03-29 00:17 UTC, jaycorpstudios commented on src/modals/AddTaskModal.js
> +      const currentDate = new Date(),
si inicializas la fecha en el state, no necesitarás inicializarla de nuevo aquí, puedes mandarla como un parámetro a esta función.

2018-03-29 00:17 UTC, jaycorpstudios commented on src/modals/AddTaskModal.js
> +  gDate() {
gDate() asumo que es por getDate... pero realmente lo que este método hace es formatear la fecha para mostrarla, puedes agregarle un nombre mas descriptivo y sin acortarlo? Recuerda que todos deben entender tu código, usar nombres descriptivos ayuda bastante.

2018-03-29 00:17 UTC, jaycorpstudios commented on src/modals/AddTaskModal.js
> +      month = months[currentDate.getMonth()],
No estoy muy seguro si ya tenemos funcionalidad parecida para dar formato a las fechas, si es así por que no crear una clase de helper para que sea reusable en toda la aplicación?

2018-03-29 00:17 UTC, jaycorpstudios commented on src/modals/AddTaskModal.js
> +                   maxDate="31-December-2019"
se que esto no está en los requerimientos pero podrías intentar fijar una fecha basado en la fecha actual + 5 años? de esa forma no sería algo estático y no tendría vencimiento realmente.

2018-03-29 00:17 UTC, jaycorpstudios commented on src/modals/AddTaskModal.js
> +                   customStyles={{
Por que no definir los customStyles en una constante y pasarla como referencia aquí? esto para no tener tanto código en la definición del componente.

2018-03-29 00:17 UTC, jaycorpstudios commented on src/modals/AddTaskModal.js
> +                     // ... You can check the source to find the other keys.
Supongo que esto lo copiaste del ejemplo que esta en la documentación, podrías borrar los comentarios que no hacen sentido con la implementación?

2018-03-29 00:17 UTC, jaycorpstudios commented on src/screens/TasksScreen.js
> +      task:{},
Para que necesitas esta propiedad en el estado? 🤔

2018-04-01 23:51 UTC, SpectreLion reviewed
Se hicieron los nuevos cambios, esperamos respuesta del profesor

2018-04-03 05:07 UTC, jaycorpstudios requested changes
Mejor la implementación, ahora si pude compilar el proyecto, sin embargo hay que corregir los detalles que te solicité para tener una mejor calidad de código.

2018-04-03 05:07 UTC, jaycorpstudios commented on src/modals/AddTaskModal.js
> +import moment from 'moment'
Insisto en este tema, realmente necesitas la librería de moment? y por que?

2018-04-03 05:07 UTC, jaycorpstudios commented on src/modals/AddTaskModal.js
> +var cd2 = new Date();
vamos a utilizar sólo sintáxis de ES6, siendo así este debería ser un "let" y aún no me queda claro la referencia del nombre de la variable, a que se refiere "cd2"? Puedes utilizar un nombre de variable que sea mas legible y entendible?

2018-04-03 05:07 UTC, jaycorpstudios commented on src/modals/AddTaskModal.js
> +const s = {
dejemos de usar abreviaciones para las variables, esto en general nunca se utiliza, const styles me parece mas legible.

2018-04-03 05:07 UTC, jaycorpstudios commented on src/modals/AddTaskModal.js
> +  wdt:{
wdt? a que hace referencia? insisto con el nombre de las variables en general.

2018-04-03 05:07 UTC, jaycorpstudios commented on src/modals/AddTaskModal.js
> +   borderColor: '#1a1d1d26'
Ya tenemos estos colores definidos en "theme/Colors.js" ? Si no es así, podrías agregarlos para que estén disponibles para todos? 

Por otro lado #1a1d1d26 no es un color hexadecimal válido, debería tener 6 caracteres solamente. podrías corregirlo? y definirlo como un RGB? puedes buscar alguna herramienta en línea para hacer la conversión. Esto para estandarizar los colores en la librería en donde los estamos definiendo.

2018-04-03 05:07 UTC, jaycorpstudios commented on src/modals/AddTaskModal.js
> +   color:'#1d1d26'
Lo mismo con este color... si no existe en la librería, hay que agregarlo y reemplazarlo aquí.

2018-04-11 00:42 UTC, jaycorpstudios approved these changes
Perfecto!

2018-04-11 00:43 UTC, merged